file: .travis.yml
language: python
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - BASE_URL=localhost:8000
    - PGPORT=5432
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest
  - pip install pytest-cov
script:
  - python manage.py test app/tests/ --settings=scratch.test_settings
  - pytest --cov=app/tests/
after_success:
  - coveralls