file: .travis.yml
language: python
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - BASE_URL=localhost:8000
    - PGPORT=5432
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='.' ./manage.py test app/tests --settings=scratch.settings
  - python coverage html
after_success:
  - coveralls