file: .travis.yml
language: python
python:
  - "3.6"
env:
  global:
    - BASE_URL=localhost:8000
install:
  - pip install -r requirements.txt
  - pip install pytest-cov==2.5.0 coverage==3.7.1 coveralls==0.5
script:  py.test --cov=app testsuite
after_success: coveralls