version: '2'

services:
  web:
    image: scratch
    build: .
    container_name: scratch.app
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=yes
      - UWSGI_PORT=8000
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    volumes:
      - static:/var/local/scratch/static

  cron:
    image: scratch
    build: .
    container_name: scratch.cron
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    entrypoint: ["./docker-entrypoint.cron.sh"]

  db:
    image: postgres:10-alpine
    container_name: scratch.db
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: scratch.elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  nginx:
    image: nginx:latest
    container_name: scratch.nginx
    environment:
      NGINX_CONF: |-
        upstream web {
          server web:8000 fail_timeout=1s;
        }
        server {
          listen 80;
          access_log /var/log/nginx/access.log main;

          location /static {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain text/css text/xml application/xml text/javascript application/javascript application/x-javascript image/x-icon;
            expires 1d;
            alias /var/local/scratch/static;
            add_header 'Access-Control-Allow-Origin' "*" always;
          }
          location / {
            proxy_pass http://web;
            proxy_set_header Host $$host;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $$remote_addr;
            gzip on;
            gzip_types text/plain text/css text/xml application/xml text/javascript application/javascript application/x-javascript image/x-icon;
            expires 1h;
          }
        }
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    restart: "always"
    depends_on:
      - web
    volumes:
      - static:/var/local/scratch/static:ro
    ports:
      - 8000:80

  smtp:
    image: eeacms/postfix
    container_name: scratch.smtp
    restart: always
    hostname: helpdesk.eaudeweb.ro
    environment:
    - MTP_HOST=${MTP_HOST}
    - MTP_RELAY=${MTP_RELAY}
    - MTP_PORT=${MTP_PORT}
    - MTP_USER=${MTP_USER}
    - MTP_PASS=${MTP_PASS}
    - MTP_DESTINATION=${MTP_DESTINATION}

volumes:
  data:
    driver: local
  static:
    driver: local
  esdata:
    driver: local
