version: '2'

services:
  web:
    image: scratch
    build: .
    container_name: scratch.app
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=no
      - UWSGI_PORT=8000
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static:/var/local/scratch/static

  db:
    image: postgres:10-alpine
    container_name: scratch.db
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: scratch.elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9205

volumes:
  data:
    driver: local
  static:
    driver: local
  esdata:
    driver: local
