version: '2'

services:
  web:
    image: eaudeweb/scratch
    container_name: scratch.app
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=yes
      - UWSGI_PORT=8000
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    volumes:
      - static:/var/local/scratch/static
    ports:
      - 8000:8000

  cron:
    image: eaudeweb/scratch
    container_name: scratch.cron
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    entrypoint: ["./docker-entrypoint.cron.sh"]

  db:
    image: postgres:10-alpine
    container_name: scratch.db
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: scratch.elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  smtp:
    image: eeacms/postfix
    container_name: scratch.smtp
    restart: always
    hostname: helpdesk.eaudeweb.ro
    environment:
    - MTP_HOST=${MTP_HOST}
    - MTP_RELAY=${MTP_RELAY}
    - MTP_PORT=${MTP_PORT}
    - MTP_USER=${MTP_USER}
    - MTP_PASS=${MTP_PASS}
    - MTP_DESTINATION=${MTP_DESTINATION}

volumes:
  data:
    driver: local
  static:
    driver: local
  esdata:
    driver: local
