version: '2'

services:
  web:
    image: eaudeweb/scratch:latest
    container_name: scratch.app
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=yes
      - UWSGI_PORT=8000
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    volumes:
      - static:/var/local/scratch/static
    ports:
      - 8000:8000

  async:
    image: eeacms/bdr.registry.notifications:latest
    container_name: not.async
    depends_on:
      - web
      - db
      - redis
      - postfix
    env_file:
      - docker/app.env
      - docker/redis.env
    environment:
      TZ: Europe/Bucharest
    volumes:
      - ./:/var/local/scratch/
    command: ['qcluster']

  cron:
    image: eaudeweb/scratch:latest
    container_name: scratch.cron
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
      - docker/app.env
    depends_on:
      - db
    entrypoint: ["./docker-entrypoint.cron.sh"]

  db:
    image: postgres:10-alpine
    container_name: scratch.db
    environment:
      - TZ=Europe/Bucharest
    env_file:
      - docker/db.env
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: scratch.elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
      image: redis:alpine
      container_name: not.redis

  smtp:
    image: eeacms/postfix
    container_name: scratch.smtp
    restart: always
    hostname: helpdesk.eaudeweb.ro
    env_file:
      - docker/app.env

volumes:
  data:
    driver: local
  static:
    driver: local
  esdata:
    driver: local
