endpoints:
  - name: Scratch
    url: #url to check
    method: GET
    timeout: 15 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
    allowed_fails: 0
    component_id: 1
    metric_id:
    action:
      - UPDATE_STATUS
      - CREATE_INCIDENT
    public_incidents: true
    latency_unit: ms
    frequency: 60
  - name: ElasticSearch
    url: #url to check
    method: GET
    timeout: 15 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
    allowed_fails: 0
    component_id: 3
    metric_id:
    action:
      - UPDATE_STATUS
      - CREATE_INCIDENT
    public_incidents: true
    latency_unit: ms
    frequency: 60
  - name: Scrach.async
    url: #url to check
    method: GET
    timeout: 15 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
    allowed_fails: 0
    component_id: 4
    metric_id:
    action:
      - UPDATE_STATUS
      - CREATE_INCIDENT
    public_incidents: true
    latency_unit: ms
    frequency: 60
  - name: Scrach.cron
    url:  #url to check
    method: GET
    timeout: 15 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
    allowed_fails: 0
    component_id: 5
    metric_id:
    action:
      - UPDATE_STATUS
      - CREATE_INCIDENT
    public_incidents: true
    latency_unit: ms
    frequency: 60
cachet:
  api_url:  # url to cachet api (e.g. https://demo.cachethq.io/api/v1)
  token:
    - type: TOKEN
      value:  #API token from cachet
messages:
  incident_outage: "{name} is unavailable"
  incident_operational: "{name} is operational"
  incident_performance: "{name} has degraded performance"
