# Generated by Django 2.2.3 on 2019-07-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('notice_type', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('published', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=5059, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('UNGM', 'UNGM'), ('TED', 'TED')], max_length=10)),
                ('unspsc_codes', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField()),
                ('source', models.CharField(choices=[('UNGM', 'UNGM'), ('TED', 'TED')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('value', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('award_date', models.DateField()),
                ('notified', models.BooleanField(default=False)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('download_url', models.CharField(max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
            ],
        ),
    ]
