# Generated by Django 2.2.3 on 2019-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNSPSCCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ungm', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
    ]
