# Generated by Django 2.2.3 on 2019-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_unspsc_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unspsccode',
            name='id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
    ]
