# Generated by Django 2.2.3 on 2019-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_unspsc_codes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPVCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
            ],
        ),
    ]
