# Generated by Django 2.2.3 on 2019-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_cpv_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpvcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='cpvcode',
            name='code',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
    ]
