# Generated by Django 2.2.3 on 2019-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_cpv_codes_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TedCountry',
            fields=[
                ('name', models.CharField(max_length=1024, primary_key=True, serialize=False)),
            ],
        ),
    ]
