# Generated by Django 2.2.3 on 2019-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_ted_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='published',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tenderdocument',
            unique_together={('name', 'tender')},
        ),
    ]
