# Generated by Django 2.2.4 on 2019-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_file_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdocument',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
