# Generated by Django 2.2.4 on 2019-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_change_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdocument',
            name='document',
            field=models.FileField(max_length=300, upload_to='documents'),
        ),
    ]
