# Generated by Django 2.2.4 on 2019-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_change_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='has_keywords',
            field=models.BooleanField(default=False),
        ),
    ]
