# Generated by Django 2.2.4 on 2019-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tender_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='has_keywords',
            field=models.BooleanField(default=False),
        ),
    ]
