# Generated by Django 2.2.4 on 2019-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tender_has_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(blank=True, max_length=255, null=True)),
                ('kwargs', models.CharField(blank=True, max_length=255, null=True)),
                ('started', models.DateTimeField(editable=False)),
                ('stopped', models.DateTimeField(blank=True, default=None, null=True)),
                ('success', models.BooleanField(blank=True, default=True, editable=False, null=True)),
            ],
        ),
    ]
