# Generated by Django 2.2.4 on 2019-09-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_add_keyword_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerlog',
            old_name='tenders_no',
            new_name='tenders_count',
        ),
    ]
