# Generated by Django 2.2.4 on 2019-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190920_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='app.Keyword'),
        ),
    ]
