# Generated by Django 2.2.4 on 2019-10-01 14:08

from django.db import migrations, models
import django.db.models.deletion


def link_vendors(apps, schema_editor):
    vendor_model = apps.get_model('app', 'Vendor')
    winner_model = apps.get_model('app', 'Winner')
    for winner in winner_model.objects.all():
        vendor, created = vendor_model.objects.get_or_create(name=winner.vendor)
        winner.vendor_link = vendor
        winner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tender_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='Winner',
            name='vendor_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Vendor'),
        ),
        migrations.RunPython(link_vendors),
        migrations.RemoveField(
            model_name='Winner',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='Winner',
            old_name='vendor_link',
            new_name='vendor',
        ),
        migrations.AlterField(
            model_name='Winner',
            name='vendor',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Vendor'),
        ),
    ]
