# Generated by Django 2.2.9 on 2020-01-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_set_text_field_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='app.Tender'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='vendors',
            field=models.ManyToManyField(related_name='awards', to='app.Vendor'),
        ),
        migrations.RenameModel(
            old_name='Winner',
            new_name='Award',
        ),
    ]
