# Generated by Django 2.2.9 on 2020-02-06 13:46

import app.fields
from django.db import migrations
from django.db.models import F
from django.db.models.functions import Lower


def forwards_func(apps, schema_editor):
    Keyword = apps.get_model("app", "Keyword")
    db_alias = schema_editor.connection.alias
    Keyword.objects.using(db_alias).annotate(
        value_lower=Lower('value')
    ).update(value=F('value_lower'))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_winner_to_award'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='keyword',
            name='value',
            field=app.fields.LowerCharField(max_length=50, unique=True),
        ),
    ]
