# Generated by Django 2.2.10 on 2020-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0029_fix_tender_keywords_related_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='EmailAddress',
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name_plural': 'email addresses'},
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
