# Generated by Django 2.2.10 on 2022-10-10 10:50

from django.db import migrations
import json

def add_cpv_codes(apps, schema_editor):
    CPVCode = apps.get_model("app", "CPVCode")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/cpv_codes.json') as f:
        cpv_codes = json.load(f)
        for code in cpv_codes:
            CPVCode.objects.using(db_alias).bulk_create([CPVCode(pk=code["pk"])])

def remove_cpv_codes(apps, schema_editor):
    CPVCode = apps.get_model("app", "CPVCode")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/cpv_codes.json') as f:
        cpv_codes = json.load(f)
        for code in cpv_codes:
            CPVCode.objects.using(db_alias).filter(pk=code["pk"]).delete()

def add_ted_countries(apps, schema_editor):
    TedCountry = apps.get_model("app", "TedCountry")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/ted_countries.json') as f:
        ted_countries = json.load(f)
        for country in ted_countries:
            TedCountry.objects.using(db_alias).bulk_create([TedCountry(pk=country["pk"])])

def remove_ted_countries(apps, schema_editor):
    TedCountry = apps.get_model("app", "TedCountry")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/ted_countries.json') as f:
        ted_countries = json.load(f)
        for country in ted_countries:
            TedCountry.objects.using(db_alias).filter(pk=country["pk"]).delete()


def add_unspsc_codes(apps, schema_editor):
    UNSPSCCode = apps.get_model("app", "UNSPSCCode")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/unspsc_codes_software.json') as f:
        unspsc_codes = json.load(f)
        for code in unspsc_codes:
            UNSPSCCode.objects.using(db_alias).bulk_create([UNSPSCCode(
                pk=code["pk"],
                id_ungm=code["fields"]["id_ungm"],
                name=code["fields"]["name"],
            )])


def remove_unspsc_codes(apps, schema_editor):
    UNSPSCCode = apps.get_model("app", "UNSPSCCode")
    db_alias = schema_editor.connection.alias
    with open('/var/local/scratch/app/fixtures/unspsc_codes_software.json') as f:
        unspsc_codes = json.load(f)
        for code in unspsc_codes:
            UNSPSCCode.objects.using(db_alias).filter(pk=code["pk"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200225_1327'),
    ]

    operations = [
        migrations.RunPython(add_cpv_codes, remove_cpv_codes),
        migrations.RunPython(add_ted_countries, remove_ted_countries),
        migrations.RunPython(add_unspsc_codes, remove_unspsc_codes),
    ]
