# Generated by Django 2.2.28 on 2022-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_add_documents_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='renewal_date',
            field=models.DateField(null=True),
        ),
    ]
