# Generated by Django 4.1.4 on 2022-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_award_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='renewal_notified',
            field=models.BooleanField(default=False),
        ),
    ]
