# Generated by Django 4.1.4 on 2023-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
