# Generated by Django 4.1.4 on 2023-01-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_award_renewal_notified'),
        ('app', '0036_tender_tags'),
    ]

    operations = [
    ]
