# Generated by Django 3.2.16 on 2023-01-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



def forwards_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("app", "Profile")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).exclude(email=""):
        Profile.objects.using(db_alias).create(user=user)

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0038_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify', models.BooleanField(default=True, help_text='Whether this user should receive email notifications or not.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
