# Generated by Django 3.2.16 on 2023-01-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
