# Generated by Django 4.1.4 on 2023-01-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_vendor_contact_name_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
