# Generated by Django 3.2.16 on 2023-01-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_tender_title_alter_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='favourite',
        ),
    ]
