# Generated by Django 3.2.16 on 2023-01-17 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0045_remove_tender_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='favorites_where_follower', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='favorites_where_inviter', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='followers',
            field=models.ManyToManyField(
                related_name='favorite_tenders', through='app.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
