# Generated by Django 4.1.6 on 2024-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEDReleaseCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oj_s', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'TED release calendar',
                'verbose_name_plural': 'TED release calendar',
            },
        ),
        migrations.AlterField(
            model_name='tender',
            name='source',
            field=models.CharField(choices=[('UNGM', 'UNGM'), ('TED', 'TED'), ('IUCN', 'IUCN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workerlog',
            name='source',
            field=models.CharField(choices=[('UNGM', 'UNGM'), ('TED', 'TED'), ('IUCN', 'IUCN')], max_length=10),
        ),
    ]
