# Generated by Django 4.1.6 on 2024-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_tedreleasecalendar_alter_tender_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEDNoticeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'TED notice code',
                'verbose_name_plural': 'TED notice codes',
            },
        ),
        migrations.AlterModelOptions(
            name='tedreleasecalendar',
            options={'ordering': ['-date'], 'verbose_name': 'TED release calendar', 'verbose_name_plural': 'TED release calendar'},
        ),
    ]
