# Generated by Django 4.1.6 on 2024-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_tednoticecode_alter_tedreleasecalendar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tednoticecode',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
