# Generated by Django 4.1.6 on 2024-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_tednoticecode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tedcountry',
            name='iso_a3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
