# Generated by Django 4.1.6 on 2024-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_tedcountry_iso_a3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tednoticecode',
            name='doc_type',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
